[webservers]
web-1 ansible_host=51.250.87.173 fqdn=fhmtulk3dksshvmso2he.auto.internal
web-2 ansible_host=51.250.0.247 fqdn=fhmooftmha5dhqqpjhkc.auto.internal

[databases]
master ansible_host=51.250.7.174 fqdn=fhm4jh5tto9r4i75q5s6.auto.internal
slave ansible_host=62.84.115.127 fqdn=fhmjk53o7a40ca9npdf6.auto.internal

[storage]
storage ansible_host=46.21.245.52 fqdn=fhm37ee532ushdnf4bj7.auto.internal
